#pragma once

#define ROBOT_INTERFACEE_MAJOR @PROJECT_VERSION_MAJOR@
#define ROBOT_INTERFACEE_MINOR @PROJECT_VERSION_MINOR@
#define ROBOT_INTERFACEE_PATCH @PROJECT_VERSION_PATCH@
#define ROBOT_INTERFACEE_VERSION "@PROJECT_VERSION@"