name: Create New Release

on:
  push:
    branches: [ "wip-initial-implementation" ]
    paths:
      - 'interfaces/**'
  pull_request:
    branches: [ "main" ]
permissions:
  contents: write


# https://stackoverflow.com/questions/57921401/push-to-origin-from-github-action/58393457#58393457

jobs:
  check-and-tag-interface:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t my-docker-image .devcontainer

      - name: Check if generated interface matches the proto file
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace --user $(id -u):$(id -g) my-docker-image /workspace/scripts/check-generated-interface.sh
          
      - name: Create a new tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG_NAME="v1.0.$(date +'%Y%m%d%H%M%S')"
          git tag $TAG_NAME
          git push origin $TAG_NAME