name: Create New Release

on:
  push:
    branches: [ "wip-initial-implementation" ]
    paths:
      - 'interfaces/**'
  pull_request:
    branches: [ "main" ]

jobs:
  generate-interface:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t my-docker-image .devcontainer

      - name: Run Generate Proto Interface in Docker
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace --user $(id -u):$(id -g) my-docker-image /workspace/scripts/generate-interface.sh

  commit-and-tag:
    runs-on: ubuntu-latest
    needs: generate-interface

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Commit changes
        run: |
          git add .
          git commit -m "Automated commit from GitHub Actions" || echo "No changes to commit"

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin HEAD:wip-initial-implementation

      - name: Create a new tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG_NAME="v1.0.$(date +'%Y%m%d%H%M%S')"
          git tag $TAG_NAME
          git push origin $TAG_NAME