name: Create New Release

on:
  push:
    branches: [ "wip-initial-implementation" ]
    paths:
      - 'interfaces/**'
  pull_request:
    branches: [ "main" ]
permissions:
  contents: write

jobs:
  generate-interface:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t my-docker-image .devcontainer

      - name: Run Generate Proto Interface in Docker
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace --user $(id -u):$(id -g) my-docker-image /workspace/scripts/generate-interface.sh

      - name: Commit generated files
        run: |
          git config --global user.name 'Frutiger Daniel'
          git config --global user.email 'daniel.frutiger@outlook.com'
          git add .
          git commit -m "Automated commit from GitHub Actions" || echo "No changes to commit"
          git push
          
      - name: Create a new tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG_NAME="v1.0.$(date +'%Y%m%d%H%M%S')"
          git tag $TAG_NAME
          git push origin $TAG_NAME